sweep:
  clim: ['access_cm2', 'ipsl_cm6a_lr', 'gfdl_esm4', 'mri_esm2_0', 'miroc6', 'mpi_esm1_2_lr']
  model_type: ['ANN']
  degree: [1, 2]
  layers: [4]
  emph_quantile: [0.5, 0.9, 0.95]
  time_scale: ['daily', 'year-month', 'month', 'season']


fixed:
  cmip_dir: '/pscratch/sd/k/kas7897/cmip6'
  ref_dir: '/pscratch/sd/k/kas7897/Livneh/unsplit/'
  train_start: 1950
  train_end: 1980
  val_start: 1981
  val_end: 1995
  trend_start: 2075
  trend_end: 2099
  epochs: 400
  testepoch: 50
  batch_size: 100
  ref: 'livneh'
  num: 'all'
  trend_analysis: True
  benchmarking: True
  logging: True
  train: True
  validation: True

available_gpus: [0, 1, 2, 3]  # <-- HERE
