sweep:
  clim: ['access_cm2']
  model_type: ['MLP']
  degree: [1, 2]
  layers: [4]
  emph_quantile: [0.5, 0.9, 0.95]
  time_scale: ['daily', 'year-month', 'julian-day', 'month', 'season']
  input_attrs: ['elev;slope;aspect', 'elev;slope;aspect;landcover']



fixed:
  cmip_dir: '/pscratch/sd/k/kas7897/cmip6'
  ref_dir: '/pscratch/sd/k/kas7897/Livneh/unsplit'
  ref_var: 'prec'
  train_start: 1979
  train_end: 2000
  val_start: 2001
  val_end: 2014
  trend_start: 2075
  trend_end: 2099
  epochs: 400
  testepoch: 50
  batch_size: 100
  ref: 'livneh'
  spatial_extent: 'all'
  trend_analysis: True
  benchmarking: True
  logging: True
  train: True
  validation: True


available_gpus: [0, 1, 2, 3]  # <-- HERE
