sweep:
  clim: ['ipsl_cm6a_lr']
  model_type: ['poly']
  degree: [1, 2, 3]
  layers: [3]
  emph_quantile: [0.5, 0.9]
  time_scale: ['daily']
  input_attrs: ['elev;slope;aspect;landcover']



fixed:

  ## data
  cmip_dir: '/pscratch/sd/k/kas7897/cmip6'
  ref_dir: '/pscratch/sd/k/kas7897/gridmet'
  ref: 'gridmet'
  ref_var: 'precipitation_amount'

  wet_dry_flag: True # if True, will use wet/dry flag in the data loader

  train_start: 1979
  train_end: 1990
  val_start: 1991
  val_end: 1995
  trend_start: 2075
  trend_end: 2099

  ## model params
  epochs: 400
  hidden_size: 64
  testepoch: 50
  batch_size: 5
  autoregression: True # if True, will use autoregressive features in the data loader
  lag: 3
  loss: ['quantile', 'rainy_day', 'spatial_correlation']
  pca_mode: False
  learning_rate: 1e-4

  ## chunking params
  chunk: True
  chunk_size: 365
  stride: 90

  ## run conditions
  trend_analysis: True
  benchmarking: True
  logging: False
  train: True
  validation: True


  ## PATHS
  save_path: '/pscratch/sd/k/kas7897/dCLIMAD_BA/outputs/jobs_test'
  logging_path: '/pscratch/sd/k/kas7897/dCLIMAD_BA/runs_revised/conus_gridmet_totalP'


  ## for spatial tests--- leave empty for strict temporal tests
  # currently spatial tests by feeding CONUS HUC2 shapefiles, and the coordiantes are grouped based on the listed HUC2s
  spatial_test: False
  shapefile_filter_path: None
  spatial_extent: [0]  #list the number of HUC2s you want to train your coordinates
  spatial_extent_val: [0] #list the number of HUC2s you want to validate your coordinates



available_gpus: [0]  # <-- HERE
