sweep:
  clim: ['access_cm2', 'gfdl_esm4', 'ipsl_cm6a_lr', 'miroc6', 'mpi_esm1_2_lr', 'mri_esm2_0']
  model_type: ['MLP']
  degree: [1, 2]
  layers: [4]
  emph_quantile: [0.5]
  time_scale: ['daily', 'julian-day', 'month', 'season']
  input_attrs: ['elev;slope;aspect;landcover']



fixed:

  ## data
  cmip_dir: '/pscratch/sd/k/kas7897/cmip6'
  ref_dir: '/pscratch/sd/k/kas7897/gridmet'
  ref: 'gridmet'
  ref_var: 'precipitation_amount'

  wet_dry_flag: True # if True, will use wet/dry flag in the data loader

  train_start: 1979
  train_end: 2000
  val_start: 2001
  val_end: 2014
  trend_start: 2075
  trend_end: 2099

  ## model params
  epochs: 400
  hidden_size: 64
  testepoch: 50
  batch_size: 100
  autoregression: True # if True, will use autoregressive features in the data loader
  lag: 3
  loss: ['quantile', 'rainy_day']
  pca_mode: True  # if True, will use Fourier mode in the model

  ## chunking params
  chunk: False
  chunk_size: 365
  stride: 90

  ## run conditions
  trend_analysis: True
  benchmarking: True
  logging: True
  train: True
  validation: True


  ## for spatial tests--- leave empty for strict temporal tests
  # currently spatial tests by feeding CONUS HUC2 shapefiles, and the coordiantes are grouped based on the listed HUC2s
  spatial_test: False
  shapefile_filter_path: None
  spatial_extent: [0]  #list the number of HUC2s you want to train your coordinates
  spatial_extent_val: [0] #list the number of HUC2s you want to validate your coordinates



available_gpus: [0, 1, 2, 3]  # <-- HERE
