sweep:
  clim: ['ipsl_cm6a_lr']
  degree: [8]   #if montone is True, degree is number of bumps
  layers: [2]
  emph_quantile: [0.5, 0.9]
  time_scale: ['daily']
  input_attrs: ['elev;slope;aspect;landcover']



fixed:

  ## data
  cmip_dir: '/pscratch/sd/k/kas7897/cmip6'
  ref_dir: '/pscratch/sd/k/kas7897/Livneh/unsplit'
  ref: 'livneh'
  ref_var: 'prec'

  wet_dry_flag: True # if True, will use wet/dry flag in the data loader

  train_start: 1979
  train_end: 1984
  val_start: 1985
  val_end: 1990
  trend_start: 2075
  trend_end: 2099

  monotone: True # if True, will use monotonicity constraint in the model

  ## model params
  transform_type: 'monotone'
  temp_enc: "LSTM"

  epochs: 500
  hidden_size: 64
  testepoch: 50
  batch_size: 5
  autoregression: True # if True, will use autoregressive features in the data loader
  lag: 3
  loss: ['quantile', 'rainy_day', spatial_correlation]
  pca_mode: False
  learning_rate: 1e-4
  neighbors: 16  #number of spatial neighbors

  ## chunking params
  chunk: True
  chunk_size: 365
  stride: 90

  ## run conditions
  trend_analysis: True
  benchmarking: True
  logging: False
  train: True
  validation: True


  ## PATHS
  save_path: '/pscratch/sd/k/kas7897/dCLIMAD_BA/outputs/jobs_test'
  logging_path: '/pscratch/sd/k/kas7897/dCLIMAD_BA/runs_revised/conus_livneh_monotone_spatioTempConv_spatialLoss'


  ## for spatial tests--- leave empty for strict temporal tests
  # currently spatial tests by feeding CONUS HUC2 shapefiles, and the coordiantes are grouped based on the listed HUC2s
  spatial_test: False
  shapefile_filter_path: None
  spatial_extent: [0]  #list the number of HUC2s you want to train your coordinates
  spatial_extent_val: [0] #list the number of HUC2s you want to validate your coordinates



available_gpus: [0]  # <-- HERE
